apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pods
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-pods
    spec:
      volumes:
        - name: pvc-mysql-dev
          persistentVolumeClaim:
            claimName: pvc-mysql-dev
      containers:
        - name: mysql-container
          image: swr.cn-north-4.myhuaweicloud.com/wmwei/mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: mysql
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: pvc-mysql-dev
              mountPath: /var/lib/mysql
              subPath: data
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always
      