apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pods
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-pods
    spec:
      containers:
        - name: mysql-container
          image: swr.cn-north-4.myhuaweicloud.com/wmwei/mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: mysql
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
      restartPolicy: Always
      