/*
 * This file is generated by jOOQ.
 */
package org.apache.servicecomb.fence.jooqdemo.db;


import java.util.Arrays;
import java.util.List;

import org.apache.servicecomb.fence.jooqdemo.db.tables.Actor;
import org.apache.servicecomb.fence.jooqdemo.db.tables.Address;
import org.apache.servicecomb.fence.jooqdemo.db.tables.Category;
import org.apache.servicecomb.fence.jooqdemo.db.tables.City;
import org.apache.servicecomb.fence.jooqdemo.db.tables.Country;
import org.apache.servicecomb.fence.jooqdemo.db.tables.Customer;
import org.apache.servicecomb.fence.jooqdemo.db.tables.Film;
import org.apache.servicecomb.fence.jooqdemo.db.tables.FilmActor;
import org.apache.servicecomb.fence.jooqdemo.db.tables.FilmCategory;
import org.apache.servicecomb.fence.jooqdemo.db.tables.Inventory;
import org.apache.servicecomb.fence.jooqdemo.db.tables.Language;
import org.apache.servicecomb.fence.jooqdemo.db.tables.Payment;
import org.apache.servicecomb.fence.jooqdemo.db.tables.PaymentP2007_01;
import org.apache.servicecomb.fence.jooqdemo.db.tables.PaymentP2007_02;
import org.apache.servicecomb.fence.jooqdemo.db.tables.PaymentP2007_03;
import org.apache.servicecomb.fence.jooqdemo.db.tables.PaymentP2007_04;
import org.apache.servicecomb.fence.jooqdemo.db.tables.PaymentP2007_05;
import org.apache.servicecomb.fence.jooqdemo.db.tables.PaymentP2007_06;
import org.apache.servicecomb.fence.jooqdemo.db.tables.Rental;
import org.apache.servicecomb.fence.jooqdemo.db.tables.Staff;
import org.apache.servicecomb.fence.jooqdemo.db.tables.Store;
import org.jooq.Catalog;
import org.jooq.Domain;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.actor</code>.
     */
    public final Actor ACTOR = Actor.ACTOR;

    /**
     * The table <code>public.address</code>.
     */
    public final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>public.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.city</code>.
     */
    public final City CITY = City.CITY;

    /**
     * The table <code>public.country</code>.
     */
    public final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>public.customer</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>public.film</code>.
     */
    public final Film FILM = Film.FILM;

    /**
     * The table <code>public.film_actor</code>.
     */
    public final FilmActor FILM_ACTOR = FilmActor.FILM_ACTOR;

    /**
     * The table <code>public.film_category</code>.
     */
    public final FilmCategory FILM_CATEGORY = FilmCategory.FILM_CATEGORY;

    /**
     * The table <code>public.inventory</code>.
     */
    public final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>public.language</code>.
     */
    public final Language LANGUAGE = Language.LANGUAGE;

    /**
     * The table <code>public.payment</code>.
     */
    public final Payment PAYMENT = Payment.PAYMENT;

    /**
     * The table <code>public.payment_p2007_01</code>.
     */
    public final PaymentP2007_01 PAYMENT_P2007_01 = PaymentP2007_01.PAYMENT_P2007_01;

    /**
     * The table <code>public.payment_p2007_02</code>.
     */
    public final PaymentP2007_02 PAYMENT_P2007_02 = PaymentP2007_02.PAYMENT_P2007_02;

    /**
     * The table <code>public.payment_p2007_03</code>.
     */
    public final PaymentP2007_03 PAYMENT_P2007_03 = PaymentP2007_03.PAYMENT_P2007_03;

    /**
     * The table <code>public.payment_p2007_04</code>.
     */
    public final PaymentP2007_04 PAYMENT_P2007_04 = PaymentP2007_04.PAYMENT_P2007_04;

    /**
     * The table <code>public.payment_p2007_05</code>.
     */
    public final PaymentP2007_05 PAYMENT_P2007_05 = PaymentP2007_05.PAYMENT_P2007_05;

    /**
     * The table <code>public.payment_p2007_06</code>.
     */
    public final PaymentP2007_06 PAYMENT_P2007_06 = PaymentP2007_06.PAYMENT_P2007_06;

    /**
     * The table <code>public.rental</code>.
     */
    public final Rental RENTAL = Rental.RENTAL;

    /**
     * The table <code>public.staff</code>.
     */
    public final Staff STAFF = Staff.STAFF;

    /**
     * The table <code>public.store</code>.
     */
    public final Store STORE = Store.STORE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Domain<?>> getDomains() {
        return Arrays.asList(
            Domains.YEAR
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Actor.ACTOR,
            Address.ADDRESS,
            Category.CATEGORY,
            City.CITY,
            Country.COUNTRY,
            Customer.CUSTOMER,
            Film.FILM,
            FilmActor.FILM_ACTOR,
            FilmCategory.FILM_CATEGORY,
            Inventory.INVENTORY,
            Language.LANGUAGE,
            Payment.PAYMENT,
            PaymentP2007_01.PAYMENT_P2007_01,
            PaymentP2007_02.PAYMENT_P2007_02,
            PaymentP2007_03.PAYMENT_P2007_03,
            PaymentP2007_04.PAYMENT_P2007_04,
            PaymentP2007_05.PAYMENT_P2007_05,
            PaymentP2007_06.PAYMENT_P2007_06,
            Rental.RENTAL,
            Staff.STAFF,
            Store.STORE
        );
    }
}
